# Generated by Django 4.2 on 2023-09-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phar',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
