# Generated by Django 4.2 on 2023-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phar', '0002_phar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phar',
            name='composition',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
