# Generated by Django 4.2 on 2023-09-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phar', '0003_phar_composition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phar',
            old_name='composition',
            new_name='sideeffects',
        ),
    ]
